variables:
  DOCKER_REGISTRY: 94310032079.dkr.ecr.us-east-1.amazonaws.com
  AWS_DEFAULT_REGION: us-east-1
  REPOSITORY_NAME: recaudo_prod_xticketing_front
  APP_NAME: v_2.0.0
  DOCKER_HOST: tcp://docker:2375 

publish:
  stage: build
  image:
    name: amazon/aws-cli
    entrypoint: [""]
  services:
    - docker:dind
  before_script:
    - amazon-linux-extras install docker
    - aws --version
    - docker --version
  script:
    - docker build -t $DOCKER_REGISTRY/$REPOSITORY_NAME:$APP_NAME . 
    - aws ecr get-login-password | docker login --username AWS --password-stdin $DOCKER_REGISTRY
    - docker push $DOCKER_REGISTRY/$REPOSITORY_NAME:$APP_NAME
  only:
    - realse
