version: 0.2
phases: 
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm install -g @angular/cli@13.0.3
  pre_build:
    commands:
      - node -v
      - ng version
      - npm i --legacy-peer-deps --force
  build:
    commands:
      - ng build --prod
artifacts:
  base-directory: dist/dist-calidad
  files:
    - '**/*'
      