version: 0.2
phases: 
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm install -g @angular/cli@14.2.12
  pre_build:
    commands:
      - npm i --legacy-peer-deps --force
  build:
    commands:
      - ng build
artifacts:
  base-directory: dist/dist-calidad
  files:
    - '**/*'
      